---
## Workflow to process the JUnit test results and add a report to the checks.
name: Test Report
on:
  workflow_run:
    workflows:
      - test
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/apm-pipeline-library/.github/actions/test-report@gh_actions
        with:
          artifact: test-results            # artifact name
          name: Test Results                # Name of the check run which will be created
          path: "**/*.json"                 # Path to test results (inside artifact .zip)
          reporter: go-json                 # Format of test results
